services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase_voting
    restart: unless-stopped
    ports:
      - "3700:8090"
    volumes:
      - pocketbase_data_voting:/pb_data
      - pocketbase_data_voting:/pb_public
      - pocketbase_data_voting:/pb_hooks
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_voting
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - VIRTUAL_HOST="voting.wildblood.dev"
      - VIRTUAL_PORT="3000"
      - CERT_NAME="wildblood.dev"
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy

volumes:
  pocketbase_data_voting:
