services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase_voting
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data_voting:/pb_data
    environment:
      VIRTUAL_HOST: "pocketbase.wildblood.dev"
      VIRTUAL_PORT: "8090"
      CERT_NAME: "wildblood.dev"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider https://pocketbase.wildblood.dev/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nginx-proxy

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_voting
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_POCKETBASE_URL: "http://pocketbase:8090"
      VIRTUAL_HOST: "voting.wildblood.dev"
      VIRTUAL_PORT: "3000"
      CERT_NAME: "wildblood.dev"
    depends_on:
      pocketbase:
        condition: service_healthy
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy

volumes:
  pocketbase_data_voting:
